#ifndef MOD_GUILDHOUSE_H
#define MOD_GUILDHOUSE_H

#include <string>

// Offsets from creatures_objects.sql
// 0-2: Talamortis (seller), Xrispins (butler), Innkeeper Monica
// 10-19: class trainers (own creature_template, cloned from real city trainers)
// 20-36: profession trainers/vendors (own creature_template, cloned from real city trainers)
constexpr uint32 GetCreatureEntry(uint32 offset)
{
    return 500030 + offset;
}

constexpr uint32 GetGameObjectEntry(uint32 offset)
{
    return 500000 + offset;
}

enum GuildHouseLocaleString : uint32
{
    GUILDHOUSE_TEXT_YOU_NOW_OWN_A_GUILD          = 1,
    GUILDHOUSE_TEXT_NOT_IN_GUILD                 = 2,
    GUILDHOUSE_TEXT_GUILD_HAS_NO_HOUSE           = 3,
    GUILDHOUSE_TEXT_HOUSE_SOLD_SUCCESS           = 4,
    GUILDHOUSE_TEXT_HOUSE_SOLD_ERROR             = 5,
    GUILDHOUSE_TEXT_HOUSE_PURCHASED_SUCCESS      = 6,
    GUILDHOUSE_TEXT_GUILD_ALREADY_HAS_HOUSE      = 7,

    GUILDHOUSE_TEXT_CMD_NEED_GUILDMASTER         = 8,
    GUILDHOUSE_TEXT_CMD_NEED_IN_GUILDHOUSE       = 9,
    GUILDHOUSE_TEXT_CMD_BUTLER_ALREADY_EXISTS    = 10,
    GUILDHOUSE_TEXT_CMD_BUTLER_ADD_ERROR         = 11,
    GUILDHOUSE_TEXT_CMD_IN_COMBAT                = 12,

    GUILDHOUSE_TEXT_BROADCAST_HOUSE_SOLD         = 20,
    GUILDHOUSE_TEXT_BROADCAST_HOUSE_PURCHASED    = 21,
    GUILDHOUSE_TEXT_BROADCAST_USE_TELEPORT       = 22,

    GUILDHOUSE_TEXT_NOT_AUTHORIZED_PURCHASE      = 30,
    GUILDHOUSE_TEXT_OBJECT_ALREADY_EXISTS        = 31,

    GUILDHOUSE_TEXT_GOSSIP_BUY_HOUSE             = 100,
    GUILDHOUSE_TEXT_GOSSIP_SELL_HOUSE_CONFIRM    = 101,
    GUILDHOUSE_TEXT_GOSSIP_TELEPORT_TO_HOUSE     = 102,
    GUILDHOUSE_TEXT_GOSSIP_CLOSE                 = 103,
    GUILDHOUSE_TEXT_GOSSIP_SELL_HOUSE            = 104,

    // Butler main menu gossip
    GUILDHOUSE_TEXT_GOSSIP_SPAWN_INNKEEPER          = 200,
    GUILDHOUSE_TEXT_GOSSIP_SPAWN_MAILBOX            = 201,
    GUILDHOUSE_TEXT_GOSSIP_SPAWN_STABLE_MASTER      = 202,
    GUILDHOUSE_TEXT_GOSSIP_SPAWN_CLASS_TRAINER      = 203,
    GUILDHOUSE_TEXT_GOSSIP_SPAWN_VENDOR_MENU        = 204,
    GUILDHOUSE_TEXT_GOSSIP_SPAWN_PORTAL_MENU        = 205,
    GUILDHOUSE_TEXT_GOSSIP_SPAWN_BANK               = 206,
    GUILDHOUSE_TEXT_GOSSIP_SPAWN_AUCTIONEER         = 207,
    GUILDHOUSE_TEXT_GOSSIP_SPAWN_NEUTRAL_AUCTIONEER = 208,
    GUILDHOUSE_TEXT_GOSSIP_SPAWN_PRIMARY_PROF       = 209,
    GUILDHOUSE_TEXT_GOSSIP_SPAWN_SECONDARY_PROF     = 210,
    GUILDHOUSE_TEXT_GOSSIP_SPAWN_SPIRIT_HEALER      = 211,
    GUILDHOUSE_TEXT_GOSSIP_GO_BACK                  = 212,

    // Butler main menu confirmations
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_INNKEEPER         = 213,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_MAILBOX           = 214,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_STABLE_MASTER     = 215,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_BANK              = 216,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_AUCTIONEER        = 217,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_NEUTRAL_AUCTIONEER = 218,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_SPIRIT_HEALER     = 219,

    // Class trainer submenu labels
    GUILDHOUSE_TEXT_TRAINER_DEATHKNIGHT          = 220,
    GUILDHOUSE_TEXT_TRAINER_DRUID                = 221,
    GUILDHOUSE_TEXT_TRAINER_HUNTER               = 222,
    GUILDHOUSE_TEXT_TRAINER_MAGE                 = 223,
    GUILDHOUSE_TEXT_TRAINER_PALADIN              = 224,
    GUILDHOUSE_TEXT_TRAINER_PRIEST               = 225,
    GUILDHOUSE_TEXT_TRAINER_ROGUE                = 226,
    GUILDHOUSE_TEXT_TRAINER_SHAMAN               = 227,
    GUILDHOUSE_TEXT_TRAINER_WARLOCK              = 228,
    GUILDHOUSE_TEXT_TRAINER_WARRIOR              = 229,

    // Class trainer submenu confirmations
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_DEATHKNIGHT    = 230,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_DRUID          = 231,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_HUNTER         = 232,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_MAGE           = 233,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_PALADIN        = 234,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_PRIEST         = 235,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_ROGUE          = 236,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_SHAMAN         = 237,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_WARLOCK        = 238,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_WARRIOR        = 239,

    // Vendor submenu labels
    GUILDHOUSE_TEXT_VENDOR_TRADE_SUPPLIES        = 300,
    GUILDHOUSE_TEXT_VENDOR_TABARD                = 301,
    GUILDHOUSE_TEXT_VENDOR_FOOD_DRINK            = 302,
    GUILDHOUSE_TEXT_VENDOR_REAGENT               = 303,
    GUILDHOUSE_TEXT_VENDOR_AMMO_REPAIR           = 304,
    GUILDHOUSE_TEXT_VENDOR_POISONS               = 305,

    // Vendor submenu confirmations
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_TRADE_SUPPLIES = 310,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_TABARD         = 311,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_FOOD_DRINK     = 312,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_REAGENT        = 313,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_AMMO_REPAIR    = 314,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_POISONS        = 315,

    // Object and portal submenu labels
    GUILDHOUSE_TEXT_OBJECT_FORGE                 = 320,
    GUILDHOUSE_TEXT_OBJECT_ANVIL                 = 321,
    GUILDHOUSE_TEXT_OBJECT_GUILD_VAULT           = 322,
    GUILDHOUSE_TEXT_OBJECT_BARBER_CHAIR          = 323,
    GUILDHOUSE_TEXT_PORTAL_IRONFORGE             = 324,
    GUILDHOUSE_TEXT_PORTAL_DARNASSUS             = 325,
    GUILDHOUSE_TEXT_PORTAL_EXODAR                = 326,
    GUILDHOUSE_TEXT_PORTAL_UNDERCITY             = 327,
    GUILDHOUSE_TEXT_PORTAL_THUNDERBLUFF          = 328,
    GUILDHOUSE_TEXT_PORTAL_SILVERMOON            = 329,
    GUILDHOUSE_TEXT_PORTAL_SHATTRATH             = 330,
    GUILDHOUSE_TEXT_PORTAL_DALARAN               = 331,

    // Object and portal submenu confirmations
    GUILDHOUSE_TEXT_CONFIRM_ADD_FORGE            = 340,
    GUILDHOUSE_TEXT_CONFIRM_ADD_ANVIL            = 341,
    GUILDHOUSE_TEXT_CONFIRM_ADD_GUILD_VAULT      = 342,
    GUILDHOUSE_TEXT_CONFIRM_ADD_BARBER_CHAIR     = 343,
    GUILDHOUSE_TEXT_CONFIRM_ADD_PORTAL_IRONFORGE = 344,
    GUILDHOUSE_TEXT_CONFIRM_ADD_PORTAL_DARNASSUS = 345,
    GUILDHOUSE_TEXT_CONFIRM_ADD_PORTAL_EXODAR    = 346,
    GUILDHOUSE_TEXT_CONFIRM_ADD_PORTAL_UNDERCITY = 347,
    GUILDHOUSE_TEXT_CONFIRM_ADD_PORTAL_THUNDERBLUFF = 348,
    GUILDHOUSE_TEXT_CONFIRM_ADD_PORTAL_SILVERMOON   = 349,
    GUILDHOUSE_TEXT_CONFIRM_ADD_PORTAL_SHATTRATH    = 350,
    GUILDHOUSE_TEXT_CONFIRM_ADD_PORTAL_DALARAN      = 351,

    // Primary profession trainer labels
    GUILDHOUSE_TEXT_PROF_TRAINER_ALCH            = 360,
    GUILDHOUSE_TEXT_PROF_TRAINER_BLACKSMITH      = 361,
    GUILDHOUSE_TEXT_PROF_TRAINER_ENGINEERING     = 362,
    GUILDHOUSE_TEXT_PROF_TRAINER_TAILORING       = 363,
    GUILDHOUSE_TEXT_PROF_TRAINER_LEATHERWORKING  = 364,
    GUILDHOUSE_TEXT_PROF_TRAINER_SKINNING        = 365,
    GUILDHOUSE_TEXT_PROF_TRAINER_MINING          = 366,
    GUILDHOUSE_TEXT_PROF_TRAINER_HERBALISM       = 367,
    GUILDHOUSE_TEXT_PROF_TRAINER_ENCHANTING      = 368,
    GUILDHOUSE_TEXT_PROF_TRAINER_JEWELCRAFTING   = 369,
    GUILDHOUSE_TEXT_PROF_TRAINER_INSCRIPTION     = 370,

    // Primary profession trainer confirmations
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_PROF_ALCH          = 380,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_PROF_BLACKSMITH    = 381,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_PROF_ENGINEERING   = 382,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_PROF_TAILORING     = 383,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_PROF_LEATHERWORKING = 384,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_PROF_SKINNING      = 385,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_PROF_MINING        = 386,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_PROF_HERBALISM     = 387,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_PROF_ENCHANTING    = 388,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_PROF_JEWELCRAFTING = 389,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_PROF_INSCRIPTION   = 390,

    // Secondary profession trainer labels
    GUILDHOUSE_TEXT_PROF_TRAINER_FIRSTAID        = 400,
    GUILDHOUSE_TEXT_PROF_TRAINER_FISHING         = 401,
    GUILDHOUSE_TEXT_PROF_TRAINER_COOKING         = 402,

    // Secondary profession trainer confirmations
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_PROF_FIRSTAID  = 410,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_PROF_FISHING   = 411,
    GUILDHOUSE_TEXT_CONFIRM_SPAWN_PROF_COOKING   = 412,

    // Guild house buy menu
    GUILDHOUSE_TEXT_GOSSIP_GM_ISLAND             = 413,
    GUILDHOUSE_TEXT_CONFIRM_BUY_GM_ISLAND        = 414
};

class Player;

// Preloads localized texts from mod_guildhouse_locale into memory
void LoadGuildHouseLocales();

// Returns localized text for the given id and player locale
std::string GetGuildHouseLocaleText(uint32 id, Player* player);

#endif // MOD_GUILDHOUSE_H
